steps:
- name: gcr.io/cloud-builders/npm
  entrypoint: npm
  args: ['install']
- name: gcr.io/cloud-builders/npm
  entrypoint: npm
  args: ['install', '-g', 'firebase-tools@5.1.1']
- name: gcr.io/cloud-builders/npm
  entrypoint: npm
  args: ['run', 'build']
  env: ['PROJECT_ID=${_PROJECT_ID}', 'TOKEN=${_TOKEN}', 'GOOGLE_CLOUD_PROJECT=${_PROJECT_ID}']
- name: gcr.io/cloud-builders/npm
  entrypoint: npm
  args: ['run', 'deploy:prod']
  env: ['PROJECT_ID=${_PROJECT_ID}', 'TOKEN=${_TOKEN}', 'GOOGLE_CLOUD_PROJECT=${_PROJECT_ID}']
- name: gcr.io/cloud-builders/npm
  entrypoint: npm
  args: ['run', 'firestore:update']
  env: ['PROJECT_ID=${_PROJECT_ID}', 'TOKEN=${_TOKEN}', 'GOOGLE_CLOUD_PROJECT=${_PROJECT_ID}', 'AUTH_KEY=${_KEY}']
substitutions:
  _PROJECT_ID: 'gdgcloud-devfest'
  _TOKEN: ''
